<div class="row message-body">
    <div class="col-sm-12 message-main-receiver">
        <div class="receiver">
            <div class="message-text">
                <?php echo $this->messageContent; ?>
            </div>
            <span class="message-time pull-right">
                <?php echo $this->myName; ?>, <?php echo $this->sendTime; ?>
              </span>
        </div>
    </div>
</div>