<div class="row message-body">
    <div class="col-sm-12 message-main-sender">
        <div class="sender">
            <div class="message-text">
                <?php echo $this->messageContent; ?>
            </div>
            <span class="message-time pull-right">
                <?php echo $this->senderName; ?>, <?php echo $this->sendTime; ?>
            </span>
        </div>
    </div>
</div>